### ISSUE TITLE
Automatic deployment

### ISSUE THREAD

**Issue by claha** [claha/smart-home#7]
The github_deploy role creates a simple service that listens for github action workflows named "Deploy xyz" and then simply runs the xyz tag using ansible.

- [x] bash - Init task which is basically expected to run once, so not adding it
- [x] docker_compose_autorestic - Will be done in #6 
- [x] docker_compose_diun
- [x] docker_compose_dozzle
- [x] docker_compose_duckdns
- [x] docker_compose_gatus
- [x] docker_compose_glances
- [x] docker_compose_homeassistant
- [x] docker_compose_homepage
- [x] docker_compose_mosquitto
- [x] docker_compose_pihole - Will be done in #19
- [x] docker_compose_piper
- [x] docker_compose_speedtest
- [x] docker_compose_tailscale
- [x] docker_compose_traefik
- [x] docker_compose_uptimekuma
- [x] docker_compose_zigbee2mqtt
- [x] github_deploy - Any security risks if doing this automatically, probably not but keep it manual for now
- [x] nixos - Will be done in #16 
- [x] ssh_config - Only intended to be run on localhost

**Comment by claha** [comment]
All current roles are now auto deployed or broken out into seperate task!
